name: FastAPI CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-fastapi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import nltk; nltk.download('punkt'); nltk.download('stopwords')"

      - name: Run FastAPI app in background
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # give the server time to start

      - name: Test FastAPI is running
        run: |
          curl -X POST "http://localhost:8000/pdf-summary" || echo "Server not responding"
